### ISSUE TITLE
How to send a beacon?

### ISSUE THREAD

**Issue by ghost** [LA3QMA/TH-D74-Kenwood#12]
I send 'PT 0'  (manual control) followed by 'BE' and I receive 'BE' (accepted). I'm on 144.39 MHz. But I don't see the transmit light come on. The radio is in 'APRS 12' mode. Is there anything else that I need to do to get this to transmit?

I just saw the wiki tab and read about the possibility of bricking the radio. Is there a way to force a factory reset if that happens?

While I was playing with this I also thought about doing the 'AA' / 'ZZ' thing. Maybe that should be done for the D75.

thanks,
Bob

**Comment by LA3QMA** [comment]
I think the radio only beacons if the position is set or the GPS has a valid position.
Also the squelch should be "closed" and the callsign should be set for aprs.

You are only able to brick the radio if you use the "0M KENWOOD" command to directly write to the radio at  the wrong plaze. I have manually changed the firmware data and uploaded.  But for this you have to wait for the writing and then the radio reboots just like when you use the firmware upgrade and/or the MCP software to write/read from the radio.

I usually only use the MCP software once and then all changes i do with the commands documented here. And its usefull if you want to control the radio.

Regarding the TH-D75 the AA/ZZ is thw quickest way to find the commands. Kenwood have compressed their software so even with a hex editor its going to take longer time than just sending the commands.

But please leave out the "TX" command. When i first discovered this my radio was on TX very long and no commands worked and then i discovered that the radio was in TX ;-) 

Also when testing commands you should test permutations like i.e

PT
PT 0
PT 0,0

And also some commands only work when other functions are enabled/disabled etc.

If the "AI" command work on the TH-D75 this is good as then you can change things on the radio and see the result in the terminal. Then you can see the expected format that the radio wants etc.

So please clone this git and rename it to TH-D75 and change/remove whats not correct. But please send me the link so that i also can link back to that.

**Comment by ghost** [comment]
I got it working. Here are the serial port and radio settings:
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1
xonxoff: False
dsrdtr: False
rtscts: False
timeout: 0.15
write_timeout: 0.15
inter_byte_timeout: None

MD: MD 0,0
FQ: FQ 0,0144390000
SQ: SQ 0,5
TN: TN 1,0

**Comment by ghost** [comment]
I haven't done the AA/ZZ test, so I haven't cloned this. Also I don't know much about doing that right now. Too busy writing code which is constantly changing.

Has anyone tried to decompile or disassemble the firmware? Do you know what processor it uses?
